//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspMailList.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class mala_direta_campanha_smtp_mail
    {
        public int id { get; set; }
        public int idCamapnha { get; set; }
        public string SmtpUser { get; set; }
        public string SmtpPassword { get; set; }
    }
}
